### ISSUE TITLE
error money field is nil

### ISSUE THREAD

**Issue by limiraweb** [LukeTowers/php-shopify-api#1]
Hello,
i retrieve an error "422 Unprocessable Entity` response: {"errors":{"order":["money field cannot be nil"]}}" when i launch the create order api.

I can't see on shopify docs any money field. How can i retrieve a response with fields with this library?

**Comment by LukeTowers** [comment]
This library wouldn't be involved with anything like that, it only is a thin wrapper around the direct HTTP API. You'd have to play around with the API calls / look for other help with the Shopify API directly as this library doesn't interact with anything that would cause that.
