### ISSUE TITLE
Package version?

### ISSUE THREAD

**Issue by chucktownguy** [LukeTowers/php-shopify-api#5]
When I run `composer require luketowers/php-shopify-api` in the site folder, I get the following error:

[InvalidArgumentException]                                                                   
Could not find a version of package luketowers/php-shopify-api matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability. 

What version should I use?

**Comment by LukeTowers** [comment]
There were no versions tagged, I usually just require `dev-master`. Tagged v1.0.0 for you so it should work now / shortly.

**Comment by chucktownguy** [comment]
This is a total noob question and I apologize ... but this is what Terminal is throwing at me when I try to install:

Problem 1

- Root composer.json requires guzzlehttp/guzzle ^6.0, found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but these were not loaded, likely because it conflicts with another require.

Problem 2

- shopify/shopify-api is locked to version v3.1.0 and an update of this package was not requested.

- shopify/shopify-api v3.1.0 requires guzzlehttp/guzzle ^7.0 -> found guzzlehttp/guzzle[7.0.0, ..., 7.5.0] but it conflicts with your root composer.json require (^6.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.



Any ideas what I'm doing wrong?

**Comment by LukeTowers** [comment]
Sounds like you're trying to load shopify/shopify-api which is a different package than this one. Try running `composer why-not shopify/shopify-api` or `composer why-not guzzlehttp/guzzle`
