### ISSUE TITLE
Can't install with current Shopify sdk

### ISSUE THREAD

**Issue by Josh5A** [LukeTowers/php-shopify-api#6]
I have a project with the Shopify API package already installed. It requires guzzle^7.0. 

When I try to install your package, I get:

- luketowers/php-shopify-api v1.0.0 requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but the package is fixed to 7.8.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by LukeTowers** [comment]
This will probably fix it: https://github.com/LukeTowers/php-shopify-api/commit/8684e687565c6bb42cae7ed87a0122edd9fd7c83
